language: python
python:
  - 3.6
  - 3.7-dev

install:
  - pip install coverage
  - pip install python-coveralls
  - pip install -e .

script:
  - coverage run --source=pybn ./pybn/utest.py

after_success:
  - coveralls
