language: python
python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install coverage
  - pip install python-coveralls
  - pip install -e .

script:
  - coverage run --source=thomas/core ./utest.py

after_success:
  - coveralls
